---
version: "3.7"

services:
  web:
    build: "."
    image: "cucmedit:latest"
    network_mode: host
    ports:
      - "5000:5000/tcp"
    volumes:
      - type: "bind"
        source: "./"
        target: "/src"
...